// +build dont_compile_me

package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"os"
	"os/exec"

	"github.com/pkg/errors"
)

const template = `// Code generated by go generate. DO NOT EDIT.
package spout

func init() {
	version = %[1]q
	commit = %[2]q
}`

func main() {
	// the version: `git describe --abbrev=0 --tags`
	ver := run("git", "describe", "--abbrev=0", "--tags")
	// the commit short hash: `git rev-parse --short HEAD`
	commit := run("git", "rev-parse", "--short", "HEAD")

	txt := fmt.Sprintf(template, ver, commit)
	if err := ioutil.WriteFile("version_init.go", []byte(txt), 0664); err != nil {
		fmt.Fprintln(os.Stderr, errors.Wrap(err, "spout/codebot"))
	}
}

func run(name string, args ...string) string {
	out, err := exec.Command(name, args...).Output()
	if err != nil {
		return "unknown"
	}
	return string(bytes.Trim(out, "\n"))
}
