// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Patterns is an autogenerated mock type for the Patterns type
type Pattern struct {
	mock.Mock
}
