// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Replacer is an autogenerated mock type for the Replacer type
type Replacer struct {
	mock.Mock
}
