// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

import rng "github.com/leesper/go_rng"

// Replacer is an autogenerated mock type for the Replacer type
type Replacer struct {
	mock.Mock
}

// ReplacedValue provides a mock function with given fields: _a0
func (_m *Replacer) ReplacedValue(_a0 *rng.GaussianGenerator) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(*rng.GaussianGenerator) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*rng.GaussianGenerator) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
