package config

// Options in the configure file.
const (
	LOGTYPE              = "logype"
	OUTPUTSTDOUT         = "outputStdout"
	OUTPUTFILE           = "outputFile"
	OUTPUTSYSLOG         = "outputSyslog"
	CONSOLEPORT          = "consolePort"
	SAMPLEFILE           = "sampleFile"
	PATTERN              = "pattern"
	REPLACEMENT          = "replacement"
	TYPE                 = "type"
	ATTRS                = "attrs"
	METHOD               = "method"
	LIST                 = "list"
	MIN                  = "min"
	MAX                  = "max"
	MININTERVAL          = "minInterval"
	MAXINTERVAL          = "maxInterval"
	DURATION             = "duration"
	MAXEVENTS            = "maxEvents"
	LISTFILE             = "listFile"
	FIXEDLIST            = "fixedList"
	TIMESTAMP            = "timestamp"
	INTEGER              = "integer"
	FLOAT                = "float"
	PRECISION            = "precision"
	STRING               = "string"
	CHARS                = "chars"
	LOOKSREAL            = "looksReal"
	FORMAT               = "format"
	CONCURRENY           = "concurrency"
	DUPLICATE            = "duplicate"
	UNIFORM              = "uniform"
	HIGHTIDE             = "hightide"
	RECONVERT            = "reConvert"
	TRANSACTION          = "transaction"
	TRANSACTIONIDS       = "transactionIDs"
	MAXINTRATRANSLATENCY = "maxIntraTransactionLatency"
)
